app:
  accounting:
    creditname: ${SECRET_TRLRS_APP_ACCOUNTING_CREDITNAME}
    debitname: ${SECRET_TRLRS_APP_ACCOUNTING_DEBITNAME}
    password: ${SECRET_TRLRS_APP_ACCOUNTING_PASSWORD}
    url: ${SECRET_TRLRS_APP_ACCOUNTING_URL}
    user: ${SECRET_TRLRS_APP_ACCOUNTING_USER}
  narrowVersions: ${SECRET_TRLRS_APP_NARROWVERSIONS}
  privatekey: ${SECRET_TRLRS_APP_PRIVATEKEY}
  propertiesdump: ${SECRET_TRLRS_APP_PROPERTIESDUMP}
  publickeypath: ${SECRET_TRLRS_APP_PUBLICKEYPATH}
  secretkey: ${SECRET_TRLRS_APP_SECRETKEY}
  security:
    dynamicPatterns: ${SECRET_TRLRS_APP_SECURITY_DYNAMICPATTERNS}
  sigpassword: ${SECRET_TRLRS_APP_SIGPASSWORD}
  tp:
    apikey: ${SECRET_TRLRS_APP_TP_APIKEY}
    landowner:
      url: ${SECRET_TRLRS_APP_TP_LANDOWNER_URL}
    password: ${SECRET_TRLRS_APP_TP_PASSWORD}
    user: ${SECRET_TRLRS_APP_TP_USER}
    value: ${SECRET_TRLRS_APP_TP_VALUE}
  transliteration:
    ai4bharat:
      enabled: ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_ENABLED}
      password: ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_PASSWORD}
      url: ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_URL}
      user: ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_USER}
logback:
  rollingpolicy:
    file-name-pattern: ${SECRET_TRLRS_LOGBACK_ROLLINGPOLICY_FILE_NAME_PATTERN}
    max-file-size: ${SECRET_TRLRS_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE}
    max-history: ${SECRET_TRLRS_LOGBACK_ROLLINGPOLICY_MAX_HISTORY}
logging:
  file:
    name: ${SECRET_TRLRS_LOGGING_FILE_NAME}
  level:
    root: ${SECRET_TRLRS_LOGGING_LEVEL_ROOT}
  pattern:
    file: ${SECRET_TRLRS_LOGGING_PATTERN_FILE}
    level: ${SECRET_TRLRS_LOGGING_PATTERN_LEVEL}
management:
  endpoint:
    health:
      show-details: ${SECRET_TRLRS_MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}
  endpoints:
    web:
      exposure:
        include: ${SECRET_TRLRS_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
server:
  port: ${SECRET_TRLRS_SERVER_PORT}
spring:
  application:
    apiPassword: ${SECRET_TRLRS_SPRING_APPLICATION_APIPASSWORD}
    apiUser: ${SECRET_TRLRS_SPRING_APPLICATION_APIUSER}
    name: ${SECRET_TRLRS_SPRING_APPLICATION_NAME}
  jackson:
    serialization:
      fail-on-empty-beans: ${SECRET_TRLRS_SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS}
springdoc.paths-to-match: ${SECRET_TRLRS_SPRINGDOC.PATHS_TO_MATCH}
