management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
spring:
  application:
    name: tripura-lrs-landownerdetails
    apiUser: ${SECRET_TRLRS_SPRING_APPLICATION_APIUSER}
    apiPassword: ${SECRET_TRLRS_SPRING_APPLICATION_APIPASSWORD}
  jackson:
    serialization:
      fail-on-empty-beans: true
app:
  narrowVersions: 1.0,1.1,1.2,1.3
  security:
    dynamicPatterns: "/actuator/health, /actuator/prometheus, /tplandownerdetails"
  tp:
    landowner:
      url: ${SECRET_TRLRS_APP_TP_LANDOWNER_URL}
    user: ${SECRET_TRLRS_APP_TP_USER}
    password: ${SECRET_TRLRS_APP_TP_PASSWORD}
    apikey: apikey
    value: ${SECRET_TRLRS_APP_TP_VALUE}
  propertiesdump : false
  privatekey : sslcert/private_key.pem
  secretkey : RBIHSECRETKEY22022023
  sigpassword : rbih
  publickeypath : sslcert/public.pub
  transliteration : 
    ai4bharat: 
      #url : http://localhost:8300/transliterate-lrs/1.0
      url : ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_URL}
      user : ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_USER}
      password : ${SECRET_TRLRS_APP_TRANSLITERATION_AI4BHARAT_PASSWORD} 
      enabled : true
  accounting: 
    creditname: ${SECRET_PD_ACCOUNTING_CREDITNAME}
    debitname: ${SECRET_PD_ACCOUNTING_DEBITNAME}
    password: ${SECRET_PD_ACCOUNTING_PASSWORD}
    url: ${SECRET_PD_ACCOUNTING_URL}
    user: ${SECRET_PD_ACCOUNTING_USERNAME}      
server:
  port: 8080
logging:
  level:
    root: INFO
  file:
    name: /var/log/tripura-lrs-landownerdetails.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n'
    level:  '%5p %mdc'
logback:
  rollingpolicy:
    file-name-pattern: 'log/archived/tripura-lrs-landownerdetails.%d{yyyy-MM-dd}.%i.log'
    max-file-size: 10MB
    max-history: 10
springdoc.paths-to-match: /tplandownerdetails/**




